### PR TITLE
Update version in install.md

### PR DESCRIPTION
**Pull request by ShalbafZadeh**
updated version from 0.8.0 to 0.8.7 and set depth=1 so instead of cloning whole repo, it will only get latest commit in that tag

### CODE REVIEW

**Comment by uglide** [comment]
hello

Thank you for your pull request.
Adding `--depth=1` is a good idea, but I don't like an idea to hardcode tag in documentation because it's information which becomes outdated in couple days (btw, latest tag is 0.8.7-1). It's better to provide a note with a link to a place where a user can find the latest stable tag.

**Comment by ShalbafZadeh** [comment]
@uglide current tag is 0.8.0 is documentation and i will undo that change if you want
i tried to edit it from [readthedocs](http://docs.redisdesktop.com/en/latest/) but edit button returns [404](https://github.com/uglide/RedisDesktopManager/edit/0.8.0/home/docs/checkouts/readthedocs.org/user_builds/redisdesktopmanager/checkouts/latest/docs/index.md)

**Comment by uglide** [comment]
0.8.0 is branch, not tag. Latest tag is 0.8.7-1
Add variable `LATEST_TAG` and add note where to copy paste it. After that i'll merge this PR

**Comment by uglide** [comment]
Hello @ShalbafZadeh 
Do you plan to update this PR?

**Comment by uglide** [comment]
I'm closing this PR since I haven't received any answer from you.
Feel free to open new PR with required fixes. Thanks!

**Pull request closed without merging**
