### PR TITLE
Update rdm_zh_CN.ts

### PR DESCRIPTION
**Pull request by andywu188**
Update rdm_zh_CN.ts

### CODE REVIEW

**Review by uglide — CHANGES_REQUESTED** [review]
Please revert layout changes to this file and apply changes to the old file layout. Currently, it's impossible to properly review changes in your PR.

**Comment by andywu188** [comment]
> Please revert layout changes to this file and apply changes to the old file layout. Currently, it's impossible to properly review changes in your PR.

This translation uses a professional translation tool "[Sisulizer](https://www.sisulizer.net/)", which takes English as the original text. After importing simplified Chinese resources, untranslated items are supplemented and simplified Chinese resources are regenerated. Compared with the content submitted before, the accuracy is completely consistent, the order of translation items is consistent with that of English resources, and some errors have been corrected, such as:

`<translation type="unfinished">使用过滤器删除键</translation>`

The following code has been corrected:

`<translation>使用过滤器删除键</translation>`


Type = "unfinished" should no longer appear in translated entries. Historical submitted versions are wrong.

I have participated in gitlab translation, and the cumulative translation items account for more than 30%, which can ensure the accuracy of translation.

Gitlab translation URL:
https://crowdin.com/translate/gitlab-ee/6/en-zhcn

User name of the translator: andywu1986

**Comment by cx405** [comment]
@andywu188 You may rethink supplying any code or translations to projects of this person, as he performs discrimination and destructive action against user groups  (public guilt) based on own  political views. As there is political and physical clash between Ukraine and Russia, he stripped it of Russian translation. At some point in future he may strip Chinese as well.

**Comment by uglide** [comment]
@andywu188 Please do not listen to stupid russian bots who never used this project. It's just hard to review all provided changes with the completely reformatted file. That's why I asked you to apply the change to the original file instead.

**Pull request closed without merging**
