### PR TITLE
update zh-CN translation

### PR DESCRIPTION
**Pull request by Jerry-Shaw**

### CODE REVIEW

**Comment by uglide** [comment]
Thanks!

**Comment by Jerry-Shaw** [comment]
I'll keep updating when seeing new content needs to be translated to Chinese simplified.

**Comment by Jerry-Shaw** [comment]
@uglide , BTW, is the translation of https://www.transifex.com/redisdesktopmanager/redisdesktopmanager/ still on work? Or, we just do the translation on github by pull requests?
Another favor, could you renew my subscription? Just noticed that, it'll be over till 2018-11-02.

**Comment by uglide** [comment]
@Jerry-Shaw transifex is not user-friendly, that's why we stick to simple pull requests for now. and I plan to setup some opensource translation tool for RDM in near future with commenting and suggesting functionality.
After expiration you will see "Get free contributor subscription" button - just press it to get your free contributor subscription (requires linked github account)

**Comment by Jerry-Shaw** [comment]
@uglide Sounds good. Suggesting function is really useful sometimes.
Good, so that I could continue using and test the latest version of RDM.

**Pull request merged**
