### PR TITLE
Update rdm_zh_TW.ts

### PR DESCRIPTION
**Pull request by weweaaa**
Update rdm_zh_TW.ts

### CODE REVIEW

**Comment by uglide** [comment]
Thanks!

**Comment by weweaaa** [comment]
Hi @uglide :
I would like to ask for your permission, how can I see the "GET FREE CONTRIBUTOR SUBSCRIPTION" button on the REST.app subscription page.

image

**Comment by uglide** [comment]
@weweaaa sign in with GitHub

**Comment by weweaaa** [comment]
Hi @uglide :

As shown in the picture in the previous message, my account is already registered with a github account.
Please tell me what is the possible reason why the button does not appear.

**Pull request merged**
