### PR TITLE
Add json syntax highlight

### PR DESCRIPTION
**Pull request by borislobanov92**
This PR contains a simple fix for #1629

@uglide looks like I messed up something with git with my last PR so I closed that one and opened a new one.

### CODE REVIEW

**Comment by uglide** [comment]
Hm, your PR stil have merge conflicts

**Comment by borislobanov92** [comment]
@uglide can you have a look now? I don't understand why github shows your commits among the changes, locally I can only see the 7 files that I have changed.

**Comment by borislobanov92** [comment]
@uglide did you have a chance to look at the PR?

**Comment by uglide** [comment]
Yes, I do. But you still need to rebase your branch on top of `2019` branch first.

**Comment by iworker** [comment]
@uglide I've just helped to fix rebasing. Check it out, please.

**Comment by uglide** [comment]
LGTM, thanks

**Pull request merged**
