### PR TITLE
(ubuntu based) linuxmint now is configured as standard ubuntu.

### LINKED ISSUE #3636: "operation system is not supported!" on ubuntu 14.04 based distro (mint 17)
RDM Version: 0.8.6 <br>
Environment (OS name and version): linux mint 17<br>

Steps to reproduce:
1. ... `git clone --recursive https://github.com/uglide/RedisDesktopManager.git -b 0.8.0 rdm && cd ./rdm`
2. ...
   `cd src/
   ./configure`

Expected result: 

it should configure ok, mint 17 it's ubuntu 14.04 based.

Actual Result: 

Your operation system is not supported!

### PR DESCRIPTION
**Pull request by Zincr0**
Fix #3636

### CODE REVIEW

**Comment by uglide** [comment]
@Zincr0 why did you change common_functions instead of configure script?

**Comment by Zincr0** [comment]
Nothing in particular, i guess that "if" could be in configure script instead.

**Comment by uglide** [comment]
Please change configure script instead of common_functions

**Comment by uglide** [comment]
@Zincr0 Do you have plans to update your pull-request?

**Comment by Zincr0** [comment]
yea, but i don't have time this days... you may close this, i will make a new pull request when i can... unless somebody else fix this before, of course.

**Comment by uglide** [comment]
ok

**Pull request closed without merging**
