### PR TITLE
Add zh_CN translation file

### PR DESCRIPTION
**Pull request by uglide**
Provided by @Jerry-Shaw

### CODE REVIEW

**Comment by Jerry-Shaw** [comment]
@uglide Hi, I made it run under VM with Chinese. Some changes are made to zh_CN, and I manager to make out the translation file for Traditional Chinese.

Two places missing, one is the "Font" in "Settings", the other one is "rename" in the Key Tab page.

Here are the language files, but my zip format cannot be support by github somehow, I can only upload TXT instead.

[rdm_zh_CN.txt](https://github.com/uglide/RedisDesktopManager/files/552453/rdm_zh_CN.txt)
[rdm_zh_TW.txt](https://github.com/uglide/RedisDesktopManager/files/552454/rdm_zh_TW.txt)

OK, wait for the next version, and we need more test.

**Comment by Jerry-Shaw** [comment]
@uglide , Hi. I got crazy busy days ago, even not finish up till now. 

Is everything OK with the translations? I might have time until the next week. 

If I can help, just let me know about it.

Once the new build comes out with the new two languages, I will test it again.

**Comment by uglide** [comment]
@Jerry-Shaw I'll update translations on Friday.

**Comment by Jerry-Shaw** [comment]
@uglide Good, so that I could test it in the weekends.

**Pull request merged**
